markdown: kramdown
kramdown:
  input: GFM

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               DynaML
tagline:             'A Scala ML library'
description:         'Library/repl for working with complex scalable ML algorithms'
url:                 https://mandar2812.github.com/DynaML
baseurl:             '/DynaML'
paginate:            5

# About/contact
author:
  name:              Mandar Chandorkar
  url:               https://twitter.com/Mandar_2812
  email:             mandar2812@gmail.com


# Custom vars
version:             1.2
