# This is your sidebar TOC. The sidebar code loops through sections here and provides the appropriate formatting.

entries:
- title: Shell Examples
  product: Shell Examples
  version: 1.0
  folders:

  - title:
    output: pdf
    type: frontmatter
    folderitems:
    - title:
      url: /titlepage
      output: pdf
      type: frontmatter
    - title:
      url: /tocpage
      output: pdf
      type: frontmatter

  - title: Introduction
    output: web, pdf
    folderitems:

    - title: Overview
      url: /p2_examples.html
      output: web

  - title: Regression
    output: web, pdf
    folderitems:

    - title: Boston Housing
      url: /p2_boston_housing.html
      output: web, pdf

  - title: Classification
    output: web, pdf
    folderitems:

    - title: Sample 6
      url: /p2_sample6.html
      output: web, pdf

  - title: System Identification
    output: web, pdf
    folderitems:
